name: conda-pak

on:
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:
    branches:
      - master
    inputs:
      release_tag:
        description: 'release tag'
        required: true

jobs:      
  mambaforge:
    name: mambaforge (${{ matrix.os }}, Mambaforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        include:
          - os: ubuntu
            miniforge-variant: Mambaforge
          - os: macos
            miniforge-variant: Mambaforge
          - os: windows
            miniforge-variant: Mambaforge
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - uses: conda-incubator/setup-miniconda@v2
        with:
          condarc-file: ${{ matrix.condarc-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}
          use-mamba: true

      - name: Get latest ninja
        # Using 'v1' branch, the most recent ninja is installed. (1.10.2)
        uses: urkle/action-get-ninja@v1

      - name: Install Requirements
        run: |
          pip install swig

      - name: pack
        run: |
          mamba install conda-build anaconda-client
          conda build ci/conda/